// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3w1Ms5ilbKiy3XuxRAlA4muuOkD7X_w',
    appId: '1:951237820554:web:3e2b8e476e174165872d73',
    messagingSenderId: '951237820554',
    projectId: 'verif-ai-8623',
    authDomain: 'verif-ai-8623.firebaseapp.com',
    storageBucket: 'verif-ai-8623.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRzuMuiz5c6NxOPy-T45i_pSbMNklaps',
    appId: '1:951237820554:android:d1ac95f2b2ed9e1a872d73',
    messagingSenderId: '951237820554',
    projectId: 'verif-ai-8623',
    storageBucket: 'verif-ai-8623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb38b0fT5s74HWiXzhJNvdy1xcTCQ5H20',
    appId: '1:951237820554:ios:1db3f273ea533cf5872d73',
    messagingSenderId: '951237820554',
    projectId: 'verif-ai-8623',
    storageBucket: 'verif-ai-8623.firebasestorage.app',
    iosBundleId: 'com.example.verityAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb38b0fT5s74HWiXzhJNvdy1xcTCQ5H20',
    appId: '1:951237820554:ios:1db3f273ea533cf5872d73',
    messagingSenderId: '951237820554',
    projectId: 'verif-ai-8623',
    storageBucket: 'verif-ai-8623.firebasestorage.app',
    iosBundleId: 'com.example.verityAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy3w1Ms5ilbKiy3XuxRAlA4muuOkD7X_w',
    appId: '1:951237820554:web:f6c9a9ca2c0ed742872d73',
    messagingSenderId: '951237820554',
    projectId: 'verif-ai-8623',
    authDomain: 'verif-ai-8623.firebaseapp.com',
    storageBucket: 'verif-ai-8623.firebasestorage.app',
  );
}
